# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci --workspace=@rain-or-shine/server --workspace=@rain-or-shine/client"]

[phases.build]
cmds = [
  "chmod +x build.sh",
  "npm run build",
  "echo '=== Final build check ==='",
  "ls -la apps/server/dist/public/ || echo 'Warning: public directory missing'"
]

[start]
cmd = "npm run start:server"

[variables]
NODE_ENV = "production"